name: laveora_admin_app
description: "LAVEORA Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  path_provider: ^2.1.0
  intl: ^0.19.0
  excel: ^4.0.0
  http: ^1.2.0
  audioplayers: ^6.0.0
  onesignal_flutter: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sounds/notification.mp3
    - assets/sounds/cash.mp3