// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZiRKZIDyF4A8ZkxvroWDhb7_nRdTAmyM',
    appId: '1:1040920797746:web:187bc3f9de94667df3d22b',
    messagingSenderId: '1040920797746',
    projectId: 'harafy-app-f693e',
    authDomain: 'harafy-app-f693e.firebaseapp.com',
    storageBucket: 'harafy-app-f693e.firebasestorage.app',
    measurementId: 'G-9Z7RP8BFVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMypIcMsVVz5gLCkE3YmEhRDEzmVX12Xk',
    appId: '1:1040920797746:android:3c81a506782a375ef3d22b',
    messagingSenderId: '1040920797746',
    projectId: 'harafy-app-f693e',
    storageBucket: 'harafy-app-f693e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcDsBUafzNN-RceeZIhO3gZDIJx1wAGVY',
    appId: '1:1040920797746:ios:ea976e67c60d1eecf3d22b',
    messagingSenderId: '1040920797746',
    projectId: 'harafy-app-f693e',
    storageBucket: 'harafy-app-f693e.firebasestorage.app',
    iosBundleId: 'com.example.laveoraAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcDsBUafzNN-RceeZIhO3gZDIJx1wAGVY',
    appId: '1:1040920797746:ios:ea976e67c60d1eecf3d22b',
    messagingSenderId: '1040920797746',
    projectId: 'harafy-app-f693e',
    storageBucket: 'harafy-app-f693e.firebasestorage.app',
    iosBundleId: 'com.example.laveoraAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZiRKZIDyF4A8ZkxvroWDhb7_nRdTAmyM',
    appId: '1:1040920797746:web:1706406c0b0b3620f3d22b',
    messagingSenderId: '1040920797746',
    projectId: 'harafy-app-f693e',
    authDomain: 'harafy-app-f693e.firebaseapp.com',
    storageBucket: 'harafy-app-f693e.firebasestorage.app',
    measurementId: 'G-TWG69Q3RDV',
  );
}
